import os
import json
import csv
import sys
from io import StringIO
from hpo_helpers.utils import *

## Convert the tunable configs except for JDK and Quarkus generated by HPO to ENV_OPTIONS
## Input: HPO config json
## Output: ENV_OPTIONS (includes SPECj CLI commands)
def get_envoptions(hpoconfigjson):
    tunables_jvm_categorical = ["TieredCompilation", "AllowParallelDefineClass", "AllowVectorizeOnDemand", "AlwaysCompileLoopMethods", "AlwaysPreTouch", "AlwaysTenure", "BackgroundCompilation", "DoEscapeAnalysis", "UseInlineCaches", "UseLoopPredicate", "UseStringDeduplication", "UseSuperWord", "UseTypeSpeculation", "StackTraceInThrowable" , "nettyBufferCheck", "gc"]
    tunables_jvm_values = ["FreqInlineSize", "MaxInlineLevel", "MinInliningThreshold", "CompileThreshold", "CompileThresholdScaling", "ConcGCThreads", "InlineSmallCode", "LoopUnrollLimit", "LoopUnrollMin", "MinSurvivorRatio", "NewRatio", "TieredStopAtLevel", "MinHeapFreeRatio", "MaxHeapFreeRatio", "GCTimeRatio", "AdaptiveSizePolicyWeight"]
    tunables_quarkus = ["quarkus.thread-pool.core-threads", "quarkus.thread-pool.queue-size", "quarkus.datasource.jdbc.min-size", "quarkus.datasource.jdbc.max-size", "quarkus.hibernate-orm.jdbc.statement-fetch-size", "quarkus.http.io-threads"]
    tunables_resources = ["memoryRequest", "cpuRequest"]
    
    # Define SPECj-specific tunables that need CLI command conversion
    specj_tunables_prefix = [
        "SUBSYSTEM_IO_WORKER_",
        "SUBSYSTEM_IO_BUFFER_POOL_",
        "SUBSYSTEM_UNDERTOW_SERVER_",
        "SUBSYSTEM_UNDERTOW_BUFFER_CACHE_",
        "SUBSYSTEM_EJB3_STRICT_MAX_BEAN_INSTANCE_POOL_",
        "SUBSYSTEM_EJB3_THREAD_POOL_",
        "SUBSYSTEM_REMOTING_",
        "SUBSYSTEM_EE_MANAGED_EXECUTOR_SERVICE_",
        "SUBSYSTEM_DATASOURCES_DATA_SOURCE_"
    ]
    
    excluded_tunables = set(tunables_jvm_categorical + tunables_jvm_values + tunables_quarkus + tunables_resources)

    with open(hpoconfigjson) as data_file:
        sstunables = json.load(data_file)

    # Separate regular ENV_OPTIONS and SPECj CLI commands
    regular_options = []
    specj_cli_commands = []
    
    for item in sstunables:
        tunable_name = item['tunable_name']
        tunable_value = item['tunable_value']
        
        # Check if this is a SPECj tunable
        is_specj_tunable = any(tunable_name.startswith(prefix) for prefix in specj_tunables_prefix)
        
        if is_specj_tunable:
            # Convert to JBoss CLI command
            cli_command = convert_specj_tunable_to_cli(tunable_name, tunable_value)
            if cli_command:
                specj_cli_commands.append(cli_command)
        elif tunable_name not in excluded_tunables:
            # Regular ENV option
            regular_options.append(f"{tunable_name}={tunable_value}")
    
    # Combine regular options and SPECj CLI commands
    ENV_OPTIONS = " ".join(regular_options)
    if specj_cli_commands:
        cli_commands_str = " ".join(specj_cli_commands)
        if ENV_OPTIONS:
            ENV_OPTIONS = f"{ENV_OPTIONS} {cli_commands_str}"
        else:
            ENV_OPTIONS = cli_commands_str
    
    ENV_OPTIONS = f'"{ENV_OPTIONS}"' if ENV_OPTIONS else ENV_OPTIONS
    print(str(ENV_OPTIONS))


def convert_specj_tunable_to_cli(tunable_name, tunable_value):
    """
    Converts a SPECj tunable to JBoss CLI write-attribute command.
    
    Tunable name format: SUBSYSTEM_<subsystem>_<resource>_<name>__<attribute>
    CLI command format: /subsystem=<subsystem>/<resource>=<name>:write-attribute(name=<attribute>,value=<value>)
    """
    # Parse the tunable name to extract components
    parts = tunable_name.split('__')
    if len(parts) != 2:
        return None
        
    path_part = parts[0]  # e.g., SUBSYSTEM_IO_WORKER_HTTPWORKER
    attribute = parts[1]  # e.g., IO_THREADS
    
    # Convert attribute to kebab-case (lowercase with hyphens)
    attribute_cli = attribute.lower().replace('_', '-')
    
    # Remove SUBSYSTEM_ prefix and split remaining parts
    path_without_prefix = path_part.replace('SUBSYSTEM_', '')
    path_components = path_without_prefix.split('_')
    
    # Build the CLI path based on the subsystem type
    cli_path = ""
    
    if path_without_prefix.startswith('IO_WORKER_'):
        # Format: /subsystem=io/worker=<name>
        worker_name = '_'.join(path_components[2:])
        worker_name_cli = worker_name[0].lower() + worker_name[1:] if len(worker_name) > 1 else worker_name.lower()
        cli_path = f"/subsystem=io/worker={worker_name_cli}"
        
    elif path_without_prefix.startswith('IO_BUFFER_POOL_'):
        # Format: /subsystem=io/buffer-pool=<name>
        pool_name = '_'.join(path_components[3:])
        pool_name_cli = pool_name[0].lower() + pool_name[1:] if len(pool_name) > 1 else pool_name.lower()
        cli_path = f"/subsystem=io/buffer-pool={pool_name_cli}"
        
    elif path_without_prefix.startswith('UNDERTOW_SERVER_DEFAULT_SERVER_HTTP_LISTENER_'):
        # Format: /subsystem=undertow/server=default-server/http-listener=<name>
        listener_name = '_'.join(path_components[5:])
        listener_name_cli = listener_name[0].lower() + listener_name[1:] if len(listener_name) > 1 else listener_name.lower()
        cli_path = f"/subsystem=undertow/server=default-server/http-listener={listener_name_cli}"
        
    elif path_without_prefix.startswith('UNDERTOW_BUFFER_CACHE_'):
        # Format: /subsystem=undertow/buffer-cache=<name>
        cache_name = '_'.join(path_components[3:])
        cache_name_cli = cache_name.lower()
        cli_path = f"/subsystem=undertow/buffer-cache={cache_name_cli}"
        
    elif path_without_prefix.startswith('EJB3_STRICT_MAX_BEAN_INSTANCE_POOL_'):
        # Format: /subsystem=ejb3/strict-max-bean-instance-pool=<name>
        pool_name = '_'.join(path_components[5:])
        pool_name_cli = pool_name.lower().replace('_', '-')
        cli_path = f"/subsystem=ejb3/strict-max-bean-instance-pool={pool_name_cli}"
        
    elif path_without_prefix.startswith('EJB3_THREAD_POOL_'):
        # Format: /subsystem=ejb3/thread-pool=<name>
        pool_name = '_'.join(path_components[3:])
        pool_name_cli = pool_name.lower()
        cli_path = f"/subsystem=ejb3/thread-pool={pool_name_cli}"
        
    elif path_without_prefix.startswith('REMOTING_'):
        # Format: /subsystem=remoting
        cli_path = "/subsystem=remoting"
        
    elif path_without_prefix.startswith('EE_MANAGED_EXECUTOR_SERVICE_'):
        # Format: /subsystem=ee/managed-executor-service=<name>
        service_name = '_'.join(path_components[4:])
        service_name_cli = service_name.lower()
        cli_path = f"/subsystem=ee/managed-executor-service={service_name_cli}"
        
    elif path_without_prefix.startswith('DATASOURCES_DATA_SOURCE_'):
        # Format: /subsystem=datasources/data-source=<name>
        ds_name = '_'.join(path_components[3:])
        # Keep original case for datasource names (SPECjInsuranceDS, etc.)
        cli_path = f"/subsystem=datasources/data-source={ds_name}"
    
    # Build the complete CLI command
    if cli_path:
        return f"{cli_path}:write-attribute(name={attribute_cli},value={tunable_value})"
    
    return None


## Convert the tunable configs of JDK and Quarkus generated by HPO to JDK_JAVA_OPTIONS
## Input: HPO config json
## Output: JDK_JAVA_OPTIONS
def get_jdkoptions(hpoconfigjson):
    tunables_jvm_categorical = ["TieredCompilation", "AllowParallelDefineClass", "AllowVectorizeOnDemand", "AlwaysCompileLoopMethods", "AlwaysPreTouch", "AlwaysTenure", "BackgroundCompilation", "DoEscapeAnalysis", "UseInlineCaches", "UseLoopPredicate", "UseStringDeduplication", "UseSuperWord", "UseTypeSpeculation", "StackTraceInThrowable" , "nettyBufferCheck", "gc"]
    tunables_jvm_values = ["FreqInlineSize", "MaxInlineLevel", "MinInliningThreshold", "CompileThreshold", "CompileThresholdScaling", "ConcGCThreads", "InlineSmallCode", "LoopUnrollLimit", "LoopUnrollMin", "MinSurvivorRatio", "NewRatio", "TieredStopAtLevel", "MinHeapFreeRatio", "MaxHeapFreeRatio", "GCTimeRatio", "AdaptiveSizePolicyWeight"]
    tunables_quarkus = ["quarkus.thread-pool.core-threads", "quarkus.thread-pool.queue-size", "quarkus.datasource.jdbc.min-size", "quarkus.datasource.jdbc.max-size", "quarkus.hibernate-orm.jdbc.statement-fetch-size", "quarkus.http.io-threads"]

    JDK_JAVA_OPTIONS = ""

    with open(hpoconfigjson) as data_file:
        sstunables = json.load(data_file)

    for st in sstunables:
        for btunable in tunables_jvm_categorical:
            if btunable == st["tunable_name"]:
                if btunable == "nettyBufferCheck":
                    if st["tunable_value"] == "true":
                        JDK_JAVA_OPTIONS = JDK_JAVA_OPTIONS + " -Dio.netty.buffer.checkBounds=true -Dio.netty.buffer.checkAccessible=true"
                    else:
                        JDK_JAVA_OPTIONS = JDK_JAVA_OPTIONS + " -Dio.netty.buffer.checkBounds=false -Dio.netty.buffer.checkAccessible=false"
                elif btunable == "gc":
                    JDK_JAVA_OPTIONS = JDK_JAVA_OPTIONS + " -XX:+Use" + st["tunable_value"]
                else:
                    if st["tunable_value"] == "true":
                        JDK_JAVA_OPTIONS = JDK_JAVA_OPTIONS + " -XX:+" + btunable
                    elif st["tunable_value"] == "false":
                        JDK_JAVA_OPTIONS = JDK_JAVA_OPTIONS + " -XX:-" + btunable

        for jvtunable in tunables_jvm_values:
            if jvtunable == st["tunable_name"]:
                if jvtunable == "ConcGCThreads":
                    ## To avoid JVM exit if ParallelGCThreads < ConcGCThreads.
                    ## Only until dependencies between tunables are set.
                    JDK_JAVA_OPTIONS = JDK_JAVA_OPTIONS + " -XX:" + jvtunable + "=" + str(st["tunable_value"]) + " -XX:ParallelGCThreads=" + str(st["tunable_value"])
                else:
                    JDK_JAVA_OPTIONS = JDK_JAVA_OPTIONS + " -XX:" + jvtunable + "=" + str(st["tunable_value"])
                
        for qtunable in tunables_quarkus:
            if qtunable == st["tunable_name"]:
                if qtunable == "quarkus.datasource.jdbc.min-size":
                    # To avoid min-size < initial-size
                    JDK_JAVA_OPTIONS = JDK_JAVA_OPTIONS + " -D" + qtunable + "=" + str(st["tunable_value"]) + " -Dquarkus.datasource.jdbc.initial-size=" + str(st["tunable_value"])
                elif qtunable == "quarkus.http.io-threads":
                    if st["tunable_value"] == "true":
                        # Get cpu request value and use it. If cpurequest is not set, do not do anything.
                        #import hpo_helpers.utils; hpo_helpers.utils.get_tunablevalue(\"hpo_config.json\", \"cpuRequest\")"
                        old_stdout = sys.stdout
                        new_stdout = StringIO()
                        sys.stdout = new_stdout
                        get_tunablevalue("hpo_config.json", "cpuRequest")
                        cpu_req = new_stdout.getvalue()
                        sys.stdout = old_stdout
                        cpu_value = int(float(cpu_req))
                        if cpu_value != "":
                            JDK_JAVA_OPTIONS = JDK_JAVA_OPTIONS + " -Dhttp.io.threads=" + str(cpu_value)
                else:
                    JDK_JAVA_OPTIONS = JDK_JAVA_OPTIONS + " -D" + qtunable + "=" + str(st["tunable_value"])

    JDK_JAVA_OPTIONS = f'"{JDK_JAVA_OPTIONS}"' if JDK_JAVA_OPTIONS else JDK_JAVA_OPTIONS
    print(str(JDK_JAVA_OPTIONS))

